version: '3.9'
services:
  web:
    container_name: web
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/nextPush
      - CODE=""
    networks:
      - my_network
  db:
    container_name: db
    image: postgres:latest
    # 坑 导致访问不了
    # volumes:
    #   - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nextPush
    networks:
      - my_network

# volumes:
#   postgres_data:


networks:
  my_network:
    driver: bridge
